# Generated by Django 3.2.4 on 2021-08-10 15:32

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOOKING_TIPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', djrichtextfield.models.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('subject', models.IntegerField(null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQQS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', djrichtextfield.models.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fcli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='happy_clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MAIN_BANNER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aimage', models.FileField(null=True, upload_to='')),
                ('bimage', models.FileField(null=True, upload_to='')),
                ('cimage', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PAYMENT_PROCEDUREs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', djrichtextfield.models.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PRIVACY_POLICYs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', djrichtextfield.models.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TERMS_CONDITIONSs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', djrichtextfield.models.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='testdrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('temporary', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('model', models.CharField(choices=[('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('Latest', 'Latest')], default='Latest', max_length=30)),
                ('fuel_type', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('other', 'other')], default='petrol', max_length=30)),
                ('kilometer', models.IntegerField(null=True)),
                ('colour', models.CharField(max_length=20, null=True)),
                ('registration_type', models.CharField(choices=[('unregistred', 'unregistred'), ('Individual', 'Individual'), ('Corporate', 'Corporate'), ('Taxi', 'Taxi'), ('commercial_registration', 'commercial_registration')], default='Individual', max_length=30)),
                ('registration_No', models.CharField(max_length=10, null=True)),
                ('Insurance', models.CharField(choices=[('comprehensive', 'comprehensive'), ('third_party', 'third_party'), ('expired', 'expired')], default='comprehensive', max_length=30)),
                ('owners', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('more_than_4', 'more_than_4')], default='1', max_length=30)),
                ('price', models.IntegerField(null=True)),
                ('discription', models.TextField(null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('image2', models.FileField(null=True, upload_to='')),
                ('image3', models.FileField(null=True, upload_to='')),
                ('image4', models.FileField(null=True, upload_to='')),
                ('image5', models.FileField(null=True, upload_to='')),
                ('image6', models.FileField(null=True, upload_to='')),
                ('image7', models.FileField(null=True, upload_to='')),
                ('image8', models.FileField(null=True, upload_to='')),
                ('image9', models.FileField(null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zbikeapp.carcategory')),
            ],
        ),
    ]
