# Generated by Django 3.2.4 on 2021-07-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('model', models.IntegerField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('price', models.IntegerField(null=True)),
                ('discription', models.TextField(null=True)),
            ],
        ),
    ]
