# Generated by Django 3.2.5 on 2021-08-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbikeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='varient',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
