# Generated by Django 3.2.4 on 2021-07-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zbikeapp', '0007_auto_20210709_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='image1',
            new_name='image',
        ),
    ]
