# Generated by Django 3.2.4 on 2021-07-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbikeapp', '0008_rename_image1_cars_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
