# Generated by Django 3.2.4 on 2021-07-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zbikeapp', '0015_auto_20210722_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='colour_family',
            new_name='colour',
        ),
    ]
