# Generated by Django 3.2.4 on 2021-07-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbikeapp', '0016_rename_colour_family_cars_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='discription',
            field=models.TextField(null=True),
        ),
    ]
