# Generated by Django 3.2.4 on 2021-07-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbikeapp', '0019_alter_cars_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
