# Generated by Django 3.1.6 on 2021-07-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbikeapp', '0020_alter_cars_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='fcli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
