# Generated by Django 3.2.4 on 2021-07-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbikeapp', '0022_verifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifications',
            name='temporary',
            field=models.IntegerField(null=True),
        ),
    ]
